#!/usr/bin/env bash

# Arguments: <add|del> <MAC> <IP> [host]

set -e

LEASE_DIR="/run/shm/leases"

[ -d "${LEASE_DIR}" ] || mkdir -p "${LEASE_DIR}"

MAC="${2}"
IP="${3}"
HOST="${4}"

if [ -z "${MAC}" -o -z "${IP}" ]; then
	logger -is "Malformed arguments (1): ${@}"
fi

add(){
	printf "${IP}\n${HOST}\n" > "${LEASE_DIR}/${MAC}"
	logger -is "DHCP ADD: ${MAC} ${IP} ${HOST}"
}

del(){
	rm -f "${LEASE_DIR}/${MAC}"
	logger -is "DHCP DEL: ${MAC} ${IP} ${HOST}"
}

case "${1}" in
	"add"|"old")
		add
		;;
	"del")
		del
		;;
	*)
		logger -is "Malformed arguments (2): ${@}"
esac

